### ISSUE TITLE
show names on mouseover doesnt remember setting

### ISSUE THREAD

**Issue by a402245** [net-lisias-ksp/DistantObject#28] opened 2022-12-17 23:09 UTC
as per title. set "show names on mouseover" to on and click apply. next time loading the game, the setting is not remembered.

**Comment by Lisias** [comment] 2023-01-15 00:08
Thank you very much for the report, @a402245 . And sorry I didn't noticed it sooner.

Github only warns me about being mentioned (i.e., using @Lisias on the text), not when someone opens an issue!

I'm working on it.

**Comment by Lisias** [comment] 2023-01-15 00:09
Cross reference: this was also reported on [Forum](https://forum.kerbalspaceprogram.com/index.php?/topic/211474-unable-to-save-config-files-for-any-add-on/&do=findComment&comment=4219645).

**Comment by Lisias** [comment] 2023-01-15 02:00
It's not only the "showNames", the "enableFlares" also is being ignored.

It's not a typo, it's some shitty code I wrote that screwed up the settings' loading somehow… 

Saving is OK.

**Comment by Lisias** [comment] 2023-01-15 03:14
Well.. Nope. Loading is partially working - the `debugMode` setting is working fine by example.

So the ConfigNode itself is being loaded fine.

I think the problem is on the KSPe's `ConfigNodeWithSteroids.HasNode` …. :/

Maybe a different misbehaviour from the same bug reported on https://github.com/net-lisias-ksp/KSPe/issues/23 ?

**Comment by Lisias** [comment] 2023-01-15 03:16
YES! The same misbehaviour! 

```
[LOG 00:12:11.839] DOE *****
[LOG 00:12:11.840] DistantFlare = DistantFlare
{
}

[LOG 00:12:11.840] DistantVessel = DistantVessel
{
}

[LOG 00:12:11.840] SkyboxBrightness = SkyboxBrightness
{
}
``

The nodes above should be filled with data, but they are empty!

**Comment by Lisias** [comment] 2023-01-15 03:35
The issue https://github.com/net-lisias-ksp/KSPe/issues/23 was bogus.

But the `KSPe.ConfigNodeWithSteroids` still have a bug on the `HasNode` method. Handling it on https://github.com/net-lisias-ksp/KSPe/issues/40

**Comment by Lisias** [comment] 2023-01-16 11:03
Closing this issue, as `KSPe.Light.DOE` was updated with the fix mentioned above.

**Closed by Lisias** 2023-01-16 11:03 UTC
Labels: bug
